//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisfracesDonZancudo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        public int id { get; set; }
        public string observacion { get; set; }
        public System.DateTime fecha_arriendo { get; set; }
        public int dias_arriendo { get; set; }
        public int cliente_id { get; set; }
        public int disfraz_id { get; set; }
        public int tipo_pago_id { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual tipo_pago tipo_pago { get; set; }
        public virtual disfraz disfraz { get; set; }
    }
}
